# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.UID }}
          password: ${{ secrets.PSD }}
          localDir: "kidsTeenYoga"
          remoteDir: "kidsTeenYoga"
#      - name: Simple FTP deploy
#        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
#        with:
#          ftp_host: ${{ secrets.HOST }}
#          ftp_username: ${{ secrets.UID }}
#          ftp_password: ${{ secrets.PSD }}
#          local_source_dir: "kidsTeenYoga"
#          dist_target_dir: "/kidsTeenYoga"